
#Tomcat
server:
  port: 8080

# Spring
spring:
  application:
    name: codemaker-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/self_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 10010hcj
  redis:
    host: 127.0.0.1 #单机配置
    post: 6379 #单机配置
    password:
    #    cluster: #集群配置
#      host:
    timeout: 1000
    database: 0
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数 默认8 ，负数表示没有限制
        max-idle: 8  # 连接池中的最大空闲连接 默认8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        min-idle: 0  # 连接池中的最小空闲连接 默认0

# Mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  type-aliases-package: com.self.codemaker.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true  # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性


# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka

# log
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread]%-5level-%highlight(%C-%M:%L)-%msg%n'
  level:
    com.self.codemaker.dao: DEBUG # 包路径为mapper文件包路径